---
apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secrets
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
  labels:
    app: {{ .Chart.Name }}
type: Opaque
data:
  mariadb-root-password: {{ randAlphaNum 16 | b64enc | quote }}
  mariadb-replication-password: {{ randAlphaNum 16 | b64enc | quote }}
  mariadb-password: {{ randAlphaNum 16 | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: akaunting-secrets
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
  labels:
    app: {{ .Chart.Name }}
type: Opaque
data:
  admin-password: {{ randAlphaNum 16 | b64enc | quote }}