---
apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secrets
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
  labels:
    app: {{ .Chart.Name }}
type: Opaque
data:
  mariadb-root-password: {{ if .Values.useRandomGeneratedValues }}
    {{- randAlphaNum 16 | b64enc | quote -}}
  {{ else }}
    {{- .Values.customSecrets.mariadbRootPassword | b64enc | quote -}}
  {{ end }}
  mariadb-replication-password: {{ if .Values.useRandomGeneratedValues }}
    {{- randAlphaNum 16 | b64enc | quote -}}
  {{ else }}
    {{- .Values.customSecrets.mariadbReplicationPassword | b64enc | quote -}}
  {{ end }}
  mariadb-password: {{ if .Values.useRandomGeneratedValues }}
    {{- randAlphaNum 16 | b64enc | quote -}}
  {{ else }}
    {{- .Values.customSecrets.mariadbPassword | b64enc | quote -}}
  {{ end }}

---
apiVersion: v1
kind: Secret
metadata:
  name: akaunting-secrets
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
  labels:
    app: {{ .Chart.Name }}
type: Opaque
data:
  admin-password: {{ if .Values.useRandomGeneratedValues }}
    {{- randAlphaNum 16 | b64enc | quote -}}
  {{ else }}
    {{- .Values.customSecrets.adminPassword | b64enc | quote -}}
  {{ end }}