#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/bjw-s/helm-charts/blob/main/charts/library/common/values.yaml
#

controllers:
  main:
    containers:
      main:
        command:
          - ninja
          - run
        image:
          # -- image repository
          repository: ghcr.io/gngpp/ninja
          # -- image tag
          # @default -- chart.appVersion
          tag: 0.8.1
          # -- image pull policy
          pullPolicy: IfNotPresent

        # -- environment variables. See more environment variables in the [ninja documentation](https://ninja.org/docs).
        # @default -- See below
        env:
          # -- Set the container timezone
          TZ: UTC
          DISABLE_DIRECT: true
          PROXIES: socks5://ninja-warp:10000
  warp:
    containers:
      main:
        image:
          # -- image repository
          repository: ghcr.io/gngpp/warp
          # -- image tag
          # @default -- chart.appVersion
          tag: latest

# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    ports:
      http:
        port: 7999
  warp:
    enabled: true
    controller: warp
    ports:
      tcp:
        port: 10000

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: false

# -- Configure persistence settings for the chart under this key.
# @default -- See values.yaml
persistence: {}
  # data:
  #   enabled: false
  #   mountPath: /data
