---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.namespace }}

spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`{{ .Values.authServerConfig.authHost }}`)
      services:
        - name: {{ .Chart.Name }}
          port: {{ .Values.service.main.ports.http.port }}
  tls:
    certResolver: {{ .Values.authServerConfig.tls.certResolver }}
