# https://kubernetes.io/docs/concepts/configuration/secret/
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.namespace }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
  labels:
    app: {{ .Chart.Name }}
type: Opaque
data:
  PROVIDERS_OIDC_CLIENT_SECRET: {{ .Values.authServerConfig.providersOidcClientSecret | b64enc | quote }}
  SECRET: {{ if .Values.useRandomGeneratedSecret }}
    {{- randBytes 16 | b64enc | quote -}}
  {{ else }}
    {{- .Values.customSecret | b64enc | quote -}}
  {{ end }}
