apiVersion: v2
appVersion: 1.0.0
description: timothyjmiller/cloudflare-ddns helm package
name: cloudflare-ddns
version: 1.0.0
kubeVersion: ">=1.22.0-0"
keywords:
  - cloudflare-ddns
home: https://github.com/ivanwongtf/nas-helm-charts/tree/master/charts/stable/cloudflare-ddns
icon: https://raw.githubusercontent.com/walkxcode/dashboard-icons/main/png/cloudflare-ddns.png
sources:
  - https://github.com/timothymiller/cloudflare-ddns
maintainers:
  - name: Ivan Wong
    email: github@ivan.bz
dependencies:
  - name: common
    version: 2.0.3
    repository: https://bjw-s.github.io/helm-charts/
annotations:
  artifacthub.io/changes: |
    - kind: added
      description: Initial version
