#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/bjw-s/helm-charts/blob/main/charts/library/common/values.yaml
#

controllers:
  main:
    containers:
      main:
        image:
          # -- image repository
          repository: timothyjmiller/cloudflare-ddns
          # -- image tag
          # @default -- chart.appVersion
          tag: latest
          # -- image pull policy
          pullPolicy: IfNotPresent

        # -- environment variables. See more environment variables in the [cloudflare-ddns documentation](https://cloudflare-ddns.org/docs).
        # @default -- See below
        env:
          # -- Set the container timezone
          TZ: UTC
          CONFIG_PATH: '/etc/cloudflare-ddns/'
        # Limit resource usage
        resources:
          limits:
            memory: '32Mi'
            cpu: '50m'

# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    enabled: false

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: false

# -- Configure persistence settings for the chart under this key.
# @default -- See values.yaml
persistence: 
  cloudflare-ddns-config:
    name: cloudflare-ddns-config
    enabled: true
    type: secret
    mountPath: /etc/cloudflare-ddns

secrets: 
  config:
    enabled: true
    stringData: 
      config.json: |
        {
          "cloudflare": [
            {
              "authentication": {
                "api_token": "api_token_here",
                "api_key": {
                  "api_key": "api_key_here",
                  "account_email": "your_email_here"
                }
              },
              "zone_id": "your_zone_id_here",
              "subdomains": [
                {
                  "name": "",
                  "proxied": false
                },
                {
                  "name": "remove_or_replace_with_your_subdomain",
                  "proxied": false
                }
              ]
            }
          ],
          "a": true,
          "aaaa": true,
          "purgeUnknownRecords": false,
          "ttl": 300
        }
